[tool.black]
line-length = 88
target-version = ["py310"]
exclude = [
  '\\.git',
  '\\.mypy_cache',
  '\\.pytest_cache',
  'build',
  'dist',
  'out',
  'reports',
  'exportToHTML',
  '__pycache__',
  'venv',
  '\\.venv',
]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = [
  "embedding_model",
  "responsibility_detector",
  "decalogo_loader",
  "spacy_loader",
  "utils",
]
skip = ["out", "reports", "exportToHTML"]

[tool.flake8]
"max-line-length" = 88
"extend-ignore" = ["E203", "W503"]
exclude = ".git,__pycache__,build,dist,out,reports,exportToHTML"
"per-file-ignores" = {"__init__.py" = "F401"}

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
pretty = true
show_error_codes = true
namespace_packages = true
follow_imports = "silent"
exclude = "(^\\.venv/|^venv/|^out/|^reports/|^exportToHTML/|^factibilidad/)"

[tool.ruff]
line-length = 88
target-version = "py310"
exclude = ["out", "reports", "exportToHTML", "build", "dist", "venv", ".venv"]
select = ["E", "F", "W", "I"]
ignore = ["E203", "W503"]

[tool.ruff.lint.isort]
known-first-party = [
  "embedding_model",
  "responsibility_detector",
  "decalogo_loader",
  "spacy_loader",
  "utils",
]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = [
  "tests",
  ".",
]
