use_clean_versions: true
paths:
  full: "out/decalogo-full.latest.clean.json"
  industrial: "out/decalogo-industrial.latest.clean.json"
  dnp: "out/dnp-standards.latest.clean.json"
crosswalk: "out/crosswalk.latest.json"
autoload: true
fail_fast: true
